; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Capacitive touchscreen
[env:JC4827W543C]
platform = espressif32
board = guition-jc4827w543c-esp32s3-N4R8
framework = arduino
board_build.partitions = huge_app.csv
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi

lib_deps =
    Arduino_GFX=https://github.com/moononournation/Arduino_GFX/archive/refs/tags/v1.6.2.zip
    TouchLib=https://github.com/mmMicky/TouchLib
    lvgl/lvgl@^8.4.0
build_flags = 
	-mfix-esp32-psram-cache-issue
	-I lib

board_upload.flash_size = 4MB
;upload_protocol = esp-builtin


; Resistive touchscreen
[env:JC4827W543R]
platform = espressif32
board = guition-jc4827w543r-esp32s3-N4R8
framework = arduino
board_build.partitions = huge_app.csv
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi

lib_deps =
    Arduino_GFX=https://github.com/moononournation/Arduino_GFX/archive/refs/tags/v1.6.2.zip
    TouchLib=https://github.com/mmMicky/TouchLib
    lvgl/lvgl@^8.4.0
build_flags = 
	-mfix-esp32-psram-cache-issue
	-I lib

board_upload.flash_size = 4MB
;upload_protocol = esp-builtin